app:  
  deployment:
    name: webapp-deployment

  service: 
    name: webapp-service
    type: NodePort
    selector: webapp
  replicas: 1
  image: dimilan/k8s-demo-app
  tag: v1.0
  containerPort: 3000
  env:
    nameUser: USER_NAME
    namePWD: USER_PWD
    nameDB: DB_URL
mongo:
  deployment:
    name: mongo-deployment
  service:
    name: mongo-servcie 
  